name: 'Compare latest pypi/pip and conda version numbers'
inputs:
  package-name:
    description: 'Name of package'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Get conda version
      run: compare_versions.sh
      shell: bash
      with:
        package_name: ${{ inputs.package-name }}