inputs:
  package-name:
    description: 'Name of package'
    required: true
runs:
  using: "composite"
  steps:
    - name: Get conda version
      run: echo "conda_version=$(conda search -c conda-forge ${{package-name}} | tail -n1 | awk '{print $2}')" >> $GITHUB_ENV
    - name: Get pip version
      run: echo "pypi_version=$(get_pypi_latest_version ${{package-name}})" >> $GITHUB_ENV
    - name: Echo Versions
      run: | 
        echo conda version=$conda_version
        echo pypi version=$pypi_version
    
    - name: Fail if versions do not match
      if: ${{ env.conda_version != env.pypi_version }}
      run: exit 1