name: Check that pip/pypi and conda versions are in sync

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.10
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - name: Add conda to system path
          run: |
            echo $CONDA/bin >> $GITHUB_PATH
        - name: Set up pip/dependencies
          run: |
            python -m pip install --upgrade pip
            pip install get_pypi_latest_version            
        - name: hipscat version check
          uses: ./.github/actions/check_versions
          with: 
            package_name: hipscat
        - name: hipscat-import version check
          uses: ./.github/actions/check_versions
          with: 
            package_name: hipscat-import
        - name: lsdb version check
          uses: ./.github/actions/check_versions
          with: 
            package_name: lsdb